### ISSUE TITLE
Building project with vite-ssg errors with: ReferenceError: self is not defined

### ISSUE THREAD

**Issue by ebisbe** [henk-badenhorst/vue-hotjar-next#8]
I'm building a Vue3 + vite project and I'm using vite-ssg. When I build the website I get the following error. 

```
ReferenceError: self is not defined
    at Object.<anonymous> (/Volumes/Data/Development/skedr/next_landing/node_modules/vue-hotjar-next/index.js:1:224)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Module.<anonymous> (/Volumes/Data/Development/skedr/next_landing/.vite-ssg-temp/main.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
error Command failed with exit code 1.
```
From what I've read the issue is in the configuration of the `webpack.js` files https://webpack.js.org/configuration/output/#outputglobalobject

Adding 
```
module.exports = {
  // ...
  output: {
    globalObject: 'this',
  },
};
``` 
Instead of the default `self` should make it work. I can do the PR but I'm not sure how that should be tested.

**Comment by ebisbe** [comment]
@henk-badenhorst can you review it? Would be helpful so I don't need to publish a package to get the fix...

**Comment by henk-badenhorst** [comment]
@ebisbe Thanks for the valuable contribution and apologies for the late reply. I was working on some other changes over the weekend with the idea to batch them up in the same release, however, in the end, I decided to exclude them. I have cherry-picked your commit and made it part of this [PR](https://github.com/henk-badenhorst/vue-hotjar-next/pull/10).

**Comment by ebisbe** [comment]
@henk-badenhorst thanks and don't worry. After that fix and due to being able to test it in local there's another small issue in #11 That one should be the last one regarding Prerrendering

**Comment by henk-badenhorst** [comment]
@ebisbe Thanks, I will add this fix along with some other enhancements. Should have it ready before the end of the week. I will close this issue and reopen #11.
